server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.pi.home
    gateway:
      routes:
        - id: front_end
          uri: lb://admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}